### ISSUE TITLE
Node modules folder absent

### ISSUE THREAD

**Issue by kamaladebayo** [drakosi99/netflix-clone-2#1]
Hey David, I cloned your repo and tried running npm start but it didn't work. I noticed `node_modules` and other files and folders were absent.

Please tell me how to get them

**Comment by peter-stuhlmann** [comment]
Node_modules can be installed with the commands "npm install" or "yarn install". The folder would be too big to upload to Github - and since you can easily install the node modules that would't be necessary.

**Comment by peter-stuhlmann** [comment]
`node_modules` can be installed with the commands `npm install` or `yarn install`. The folder would be too big to upload to Github - and since you can easily install the node modules that would't be necessary.

**Comment by kamaladebayo** [comment]
I figured out. Thanks

**Comment by kamaladebayo** [comment]
I figured out. Thanks
